name: Build C++

on:
  push:
    branches: [ main, ci-workflow ]
  pull_request:
    branches: [ main, ci-workflow ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y -f build-essential g++ cmake
  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build project
        run: g++ -Werror -Wall -Wpedantic -Wextra -std=c++20 main.cpp -o ci_for_swe_test
